version: "3.7"
services:
    planet:
        build: ./planet
        ports:
            - "50051:50051"
    star:
        build: ./star
        ports:
            - "50052:50052"
    nasa:
        build: ./nasa
        ports:
            - "50053:50053"
    app:
        build: .
        ports: 
            - "8080:8080"
    client:
        build: ./client
        ports: 
            - "8081:8081"
    mongodb_container: 
        image: mongo:latest
        container_name: 'mongodb_container'
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data_container:/data/db
volumes:
    mongodb_data_container: