// Code generated by protoc-gen-go. DO NOT EDIT.
// source: planet/planetpb/planet.proto

package planetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// We can define our planet and all of its corresponding data here, we can split this up later if we want.
type Planet struct {
	PlanetId             string            `protobuf:"bytes,1,opt,name=planet_id,json=planetId,proto3" json:"planet_id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Facts                []*Facts          `protobuf:"bytes,3,rep,name=facts,proto3" json:"facts,omitempty"`
	Image                string            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	BasicInformation     *BasicInformation `protobuf:"bytes,5,opt,name=basic_information,json=basicInformation,proto3" json:"basic_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Planet) Reset()         { *m = Planet{} }
func (m *Planet) String() string { return proto.CompactTextString(m) }
func (*Planet) ProtoMessage()    {}
func (*Planet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{0}
}

func (m *Planet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Planet.Unmarshal(m, b)
}
func (m *Planet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Planet.Marshal(b, m, deterministic)
}
func (m *Planet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Planet.Merge(m, src)
}
func (m *Planet) XXX_Size() int {
	return xxx_messageInfo_Planet.Size(m)
}
func (m *Planet) XXX_DiscardUnknown() {
	xxx_messageInfo_Planet.DiscardUnknown(m)
}

var xxx_messageInfo_Planet proto.InternalMessageInfo

func (m *Planet) GetPlanetId() string {
	if m != nil {
		return m.PlanetId
	}
	return ""
}

func (m *Planet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Planet) GetFacts() []*Facts {
	if m != nil {
		return m.Facts
	}
	return nil
}

func (m *Planet) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Planet) GetBasicInformation() *BasicInformation {
	if m != nil {
		return m.BasicInformation
	}
	return nil
}

type Facts struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Fact                 string   `protobuf:"bytes,2,opt,name=fact,proto3" json:"fact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facts) Reset()         { *m = Facts{} }
func (m *Facts) String() string { return proto.CompactTextString(m) }
func (*Facts) ProtoMessage()    {}
func (*Facts) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{1}
}

func (m *Facts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facts.Unmarshal(m, b)
}
func (m *Facts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facts.Marshal(b, m, deterministic)
}
func (m *Facts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facts.Merge(m, src)
}
func (m *Facts) XXX_Size() int {
	return xxx_messageInfo_Facts.Size(m)
}
func (m *Facts) XXX_DiscardUnknown() {
	xxx_messageInfo_Facts.DiscardUnknown(m)
}

var xxx_messageInfo_Facts proto.InternalMessageInfo

func (m *Facts) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Facts) GetFact() string {
	if m != nil {
		return m.Fact
	}
	return ""
}

type BasicInformation struct {
	AlternateName        string   `protobuf:"bytes,1,opt,name=alternate_name,json=alternateName,proto3" json:"alternate_name,omitempty"`
	NumberOfSatelites    int32    `protobuf:"varint,2,opt,name=number_of_satelites,json=numberOfSatelites,proto3" json:"number_of_satelites,omitempty"`
	StarSystem           string   `protobuf:"bytes,3,opt,name=star_system,json=starSystem,proto3" json:"star_system,omitempty"`
	MostAbundantResource string   `protobuf:"bytes,4,opt,name=most_abundant_resource,json=mostAbundantResource,proto3" json:"most_abundant_resource,omitempty"`
	SurfaceGravity       float64  `protobuf:"fixed64,5,opt,name=surface_gravity,json=surfaceGravity,proto3" json:"surface_gravity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicInformation) Reset()         { *m = BasicInformation{} }
func (m *BasicInformation) String() string { return proto.CompactTextString(m) }
func (*BasicInformation) ProtoMessage()    {}
func (*BasicInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{2}
}

func (m *BasicInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicInformation.Unmarshal(m, b)
}
func (m *BasicInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicInformation.Marshal(b, m, deterministic)
}
func (m *BasicInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicInformation.Merge(m, src)
}
func (m *BasicInformation) XXX_Size() int {
	return xxx_messageInfo_BasicInformation.Size(m)
}
func (m *BasicInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicInformation.DiscardUnknown(m)
}

var xxx_messageInfo_BasicInformation proto.InternalMessageInfo

func (m *BasicInformation) GetAlternateName() string {
	if m != nil {
		return m.AlternateName
	}
	return ""
}

func (m *BasicInformation) GetNumberOfSatelites() int32 {
	if m != nil {
		return m.NumberOfSatelites
	}
	return 0
}

func (m *BasicInformation) GetStarSystem() string {
	if m != nil {
		return m.StarSystem
	}
	return ""
}

func (m *BasicInformation) GetMostAbundantResource() string {
	if m != nil {
		return m.MostAbundantResource
	}
	return ""
}

func (m *BasicInformation) GetSurfaceGravity() float64 {
	if m != nil {
		return m.SurfaceGravity
	}
	return 0
}

type ReadPlanetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPlanetRequest) Reset()         { *m = ReadPlanetRequest{} }
func (m *ReadPlanetRequest) String() string { return proto.CompactTextString(m) }
func (*ReadPlanetRequest) ProtoMessage()    {}
func (*ReadPlanetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{3}
}

func (m *ReadPlanetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPlanetRequest.Unmarshal(m, b)
}
func (m *ReadPlanetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPlanetRequest.Marshal(b, m, deterministic)
}
func (m *ReadPlanetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPlanetRequest.Merge(m, src)
}
func (m *ReadPlanetRequest) XXX_Size() int {
	return xxx_messageInfo_ReadPlanetRequest.Size(m)
}
func (m *ReadPlanetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPlanetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPlanetRequest proto.InternalMessageInfo

func (m *ReadPlanetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReadPlanetResponse struct {
	Planet               *Planet  `protobuf:"bytes,1,opt,name=planet,proto3" json:"planet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPlanetResponse) Reset()         { *m = ReadPlanetResponse{} }
func (m *ReadPlanetResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPlanetResponse) ProtoMessage()    {}
func (*ReadPlanetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{4}
}

func (m *ReadPlanetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPlanetResponse.Unmarshal(m, b)
}
func (m *ReadPlanetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPlanetResponse.Marshal(b, m, deterministic)
}
func (m *ReadPlanetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPlanetResponse.Merge(m, src)
}
func (m *ReadPlanetResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPlanetResponse.Size(m)
}
func (m *ReadPlanetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPlanetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPlanetResponse proto.InternalMessageInfo

func (m *ReadPlanetResponse) GetPlanet() *Planet {
	if m != nil {
		return m.Planet
	}
	return nil
}

type ListPlanetRequest struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlanetRequest) Reset()         { *m = ListPlanetRequest{} }
func (m *ListPlanetRequest) String() string { return proto.CompactTextString(m) }
func (*ListPlanetRequest) ProtoMessage()    {}
func (*ListPlanetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{5}
}

func (m *ListPlanetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanetRequest.Unmarshal(m, b)
}
func (m *ListPlanetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanetRequest.Marshal(b, m, deterministic)
}
func (m *ListPlanetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanetRequest.Merge(m, src)
}
func (m *ListPlanetRequest) XXX_Size() int {
	return xxx_messageInfo_ListPlanetRequest.Size(m)
}
func (m *ListPlanetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanetRequest proto.InternalMessageInfo

func (m *ListPlanetRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type ListPlanetResponse struct {
	Planet               []*Planet `protobuf:"bytes,1,rep,name=planet,proto3" json:"planet,omitempty"`
	NumberOfDocuments    int64     `protobuf:"varint,2,opt,name=number_of_documents,json=numberOfDocuments,proto3" json:"number_of_documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListPlanetResponse) Reset()         { *m = ListPlanetResponse{} }
func (m *ListPlanetResponse) String() string { return proto.CompactTextString(m) }
func (*ListPlanetResponse) ProtoMessage()    {}
func (*ListPlanetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{6}
}

func (m *ListPlanetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlanetResponse.Unmarshal(m, b)
}
func (m *ListPlanetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlanetResponse.Marshal(b, m, deterministic)
}
func (m *ListPlanetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlanetResponse.Merge(m, src)
}
func (m *ListPlanetResponse) XXX_Size() int {
	return xxx_messageInfo_ListPlanetResponse.Size(m)
}
func (m *ListPlanetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlanetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlanetResponse proto.InternalMessageInfo

func (m *ListPlanetResponse) GetPlanet() []*Planet {
	if m != nil {
		return m.Planet
	}
	return nil
}

func (m *ListPlanetResponse) GetNumberOfDocuments() int64 {
	if m != nil {
		return m.NumberOfDocuments
	}
	return 0
}

func init() {
	proto.RegisterType((*Planet)(nil), "planet.Planet")
	proto.RegisterType((*Facts)(nil), "planet.Facts")
	proto.RegisterType((*BasicInformation)(nil), "planet.BasicInformation")
	proto.RegisterType((*ReadPlanetRequest)(nil), "planet.ReadPlanetRequest")
	proto.RegisterType((*ReadPlanetResponse)(nil), "planet.ReadPlanetResponse")
	proto.RegisterType((*ListPlanetRequest)(nil), "planet.ListPlanetRequest")
	proto.RegisterType((*ListPlanetResponse)(nil), "planet.ListPlanetResponse")
}

func init() {
	proto.RegisterFile("planet/planetpb/planet.proto", fileDescriptor_4e7ae48ba9b9a6fb)
}

var fileDescriptor_4e7ae48ba9b9a6fb = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x71, 0x13, 0xb5, 0x13, 0x25, 0x34, 0x4b, 0x85, 0x4c, 0x41, 0x22, 0x32, 0x82, 0xe4,
	0x14, 0x44, 0xe0, 0xc8, 0x85, 0x16, 0x8a, 0x2a, 0x21, 0x40, 0xce, 0x8d, 0x8b, 0xb5, 0xb6, 0xc7,
	0xd5, 0x0a, 0x7b, 0x6d, 0x76, 0xc7, 0x95, 0xfa, 0x28, 0x3c, 0x0b, 0x4f, 0xc4, 0x5b, 0x20, 0xef,
	0x4f, 0x5d, 0x9a, 0xf6, 0xe4, 0xd9, 0xef, 0x1b, 0x7f, 0x33, 0xf3, 0xcd, 0x2e, 0x3c, 0x6b, 0x2b,
	0x2e, 0x91, 0x5e, 0xdb, 0x4f, 0x9b, 0xb9, 0x60, 0xdd, 0xaa, 0x86, 0x1a, 0x36, 0xb6, 0xa7, 0xf8,
	0x4f, 0x00, 0xe3, 0xef, 0x26, 0x64, 0x4f, 0xe1, 0xc0, 0x82, 0xa9, 0x28, 0xa2, 0x60, 0x11, 0xac,
	0x0e, 0x92, 0x7d, 0x0b, 0x9c, 0x17, 0x8c, 0xc1, 0x9e, 0xe4, 0x35, 0x46, 0x0f, 0x0c, 0x6e, 0x62,
	0xf6, 0x02, 0x46, 0x25, 0xcf, 0x49, 0x47, 0xe1, 0x22, 0x5c, 0x4d, 0x36, 0xd3, 0xb5, 0xab, 0x70,
	0xd6, 0x83, 0x89, 0xe5, 0xd8, 0x11, 0x8c, 0x44, 0xcd, 0x2f, 0x30, 0xda, 0x33, 0x7f, 0xda, 0x03,
	0xfb, 0x04, 0xf3, 0x8c, 0x6b, 0x91, 0xa7, 0x42, 0x96, 0x8d, 0xaa, 0x39, 0x89, 0x46, 0x46, 0xa3,
	0x45, 0xb0, 0x9a, 0x6c, 0x22, 0x2f, 0x73, 0xd2, 0x27, 0x9c, 0x0f, 0x7c, 0x72, 0x98, 0xdd, 0x42,
	0xe2, 0x37, 0x30, 0x3a, 0xf3, 0x55, 0x48, 0x50, 0x85, 0xae, 0x6f, 0x7b, 0xe8, 0x9b, 0xee, 0x9b,
	0xf0, 0x4d, 0xf7, 0x71, 0xfc, 0x37, 0x80, 0xc3, 0xdb, 0xca, 0xec, 0x25, 0xcc, 0x78, 0x45, 0xa8,
	0x24, 0x27, 0x4c, 0xcd, 0x9c, 0x56, 0x67, 0x7a, 0x8d, 0x7e, 0xed, 0x07, 0x5e, 0xc3, 0x23, 0xd9,
	0xd5, 0x19, 0xaa, 0xb4, 0x29, 0x53, 0xcd, 0x09, 0x2b, 0x41, 0xa8, 0x8d, 0xfc, 0x28, 0x99, 0x5b,
	0xea, 0x5b, 0xb9, 0xf5, 0x04, 0x7b, 0x0e, 0x13, 0x4d, 0x5c, 0xa5, 0xfa, 0x4a, 0x13, 0xd6, 0x51,
	0x68, 0x34, 0xa1, 0x87, 0xb6, 0x06, 0x61, 0xef, 0xe0, 0x71, 0xdd, 0x68, 0x4a, 0x79, 0xd6, 0xc9,
	0x82, 0x4b, 0x4a, 0x15, 0xea, 0xa6, 0x53, 0xb9, 0x77, 0xeb, 0xa8, 0x67, 0x3f, 0x38, 0x32, 0x71,
	0x1c, 0x5b, 0xc2, 0x43, 0xdd, 0xa9, 0x92, 0xe7, 0x98, 0x5e, 0x28, 0x7e, 0x29, 0xe8, 0xca, 0x58,
	0x17, 0x24, 0x33, 0x07, 0x7f, 0xb6, 0x68, 0xbc, 0x84, 0x79, 0x82, 0xbc, 0xb0, 0xfb, 0x4d, 0xf0,
	0x57, 0x87, 0x9a, 0xae, 0x37, 0x19, 0x0c, 0x9b, 0x8c, 0xdf, 0x03, 0xbb, 0x99, 0xa8, 0xdb, 0x46,
	0x6a, 0x64, 0xaf, 0xc0, 0xdd, 0x12, 0x93, 0x3b, 0xd9, 0xcc, 0xfc, 0x66, 0x5c, 0x9e, 0xbf, 0x43,
	0x4b, 0x98, 0x7f, 0x11, 0x9a, 0x76, 0xca, 0xe8, 0x9f, 0xa2, 0x35, 0xbf, 0x86, 0x89, 0x89, 0xe3,
	0x0a, 0xd8, 0xcd, 0xc4, 0x3b, 0xca, 0x84, 0xf7, 0x97, 0xf9, 0xdf, 0xfd, 0xa2, 0xc9, 0xbb, 0x1a,
	0x25, 0x59, 0xf7, 0xc3, 0xc1, 0xfd, 0x8f, 0x9e, 0xd8, 0xfc, 0x0e, 0x60, 0x6a, 0x25, 0xb6, 0xa8,
	0x2e, 0x45, 0x8e, 0xec, 0x14, 0x60, 0x18, 0x93, 0x3d, 0xf1, 0x75, 0x76, 0x3c, 0x3a, 0x3e, 0xbe,
	0x8b, 0x72, 0xed, 0x9e, 0x02, 0x0c, 0x43, 0x0c, 0x22, 0x3b, 0x0e, 0x0c, 0x22, 0xbb, 0x33, 0x9f,
	0xc0, 0x8f, 0x7d, 0xff, 0x2e, 0xb3, 0xb1, 0x79, 0x91, 0x6f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x19, 0x3e, 0x28, 0x2c, 0xb1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlanetServiceClient is the client API for PlanetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlanetServiceClient interface {
	ReadPlanet(ctx context.Context, in *ReadPlanetRequest, opts ...grpc.CallOption) (*ReadPlanetResponse, error)
	ListPlanet(ctx context.Context, in *ListPlanetRequest, opts ...grpc.CallOption) (*ListPlanetResponse, error)
}

type planetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanetServiceClient(cc grpc.ClientConnInterface) PlanetServiceClient {
	return &planetServiceClient{cc}
}

func (c *planetServiceClient) ReadPlanet(ctx context.Context, in *ReadPlanetRequest, opts ...grpc.CallOption) (*ReadPlanetResponse, error) {
	out := new(ReadPlanetResponse)
	err := c.cc.Invoke(ctx, "/planet.PlanetService/ReadPlanet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planetServiceClient) ListPlanet(ctx context.Context, in *ListPlanetRequest, opts ...grpc.CallOption) (*ListPlanetResponse, error) {
	out := new(ListPlanetResponse)
	err := c.cc.Invoke(ctx, "/planet.PlanetService/ListPlanet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanetServiceServer is the server API for PlanetService service.
type PlanetServiceServer interface {
	ReadPlanet(context.Context, *ReadPlanetRequest) (*ReadPlanetResponse, error)
	ListPlanet(context.Context, *ListPlanetRequest) (*ListPlanetResponse, error)
}

// UnimplementedPlanetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlanetServiceServer struct {
}

func (*UnimplementedPlanetServiceServer) ReadPlanet(ctx context.Context, req *ReadPlanetRequest) (*ReadPlanetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPlanet not implemented")
}
func (*UnimplementedPlanetServiceServer) ListPlanet(ctx context.Context, req *ListPlanetRequest) (*ListPlanetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlanet not implemented")
}

func RegisterPlanetServiceServer(s *grpc.Server, srv PlanetServiceServer) {
	s.RegisterService(&_PlanetService_serviceDesc, srv)
}

func _PlanetService_ReadPlanet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPlanetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetServiceServer).ReadPlanet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/planet.PlanetService/ReadPlanet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetServiceServer).ReadPlanet(ctx, req.(*ReadPlanetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanetService_ListPlanet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlanetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetServiceServer).ListPlanet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/planet.PlanetService/ListPlanet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetServiceServer).ListPlanet(ctx, req.(*ListPlanetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlanetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "planet.PlanetService",
	HandlerType: (*PlanetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPlanet",
			Handler:    _PlanetService_ReadPlanet_Handler,
		},
		{
			MethodName: "ListPlanet",
			Handler:    _PlanetService_ListPlanet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "planet/planetpb/planet.proto",
}
