// Code generated by protoc-gen-go. DO NOT EDIT.
// source: star/starpb/star.proto

package starpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// We can define our star and all of its corresponding data here, we can split this up later if we want.
type Star struct {
	StarId               string            `protobuf:"bytes,1,opt,name=star_id,json=starId,proto3" json:"star_id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Facts                []*Facts          `protobuf:"bytes,3,rep,name=facts,proto3" json:"facts,omitempty"`
	Image                string            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	BasicInformation     *BasicInformation `protobuf:"bytes,5,opt,name=basic_information,json=basicInformation,proto3" json:"basic_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Star) Reset()         { *m = Star{} }
func (m *Star) String() string { return proto.CompactTextString(m) }
func (*Star) ProtoMessage()    {}
func (*Star) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{0}
}

func (m *Star) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Star.Unmarshal(m, b)
}
func (m *Star) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Star.Marshal(b, m, deterministic)
}
func (m *Star) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Star.Merge(m, src)
}
func (m *Star) XXX_Size() int {
	return xxx_messageInfo_Star.Size(m)
}
func (m *Star) XXX_DiscardUnknown() {
	xxx_messageInfo_Star.DiscardUnknown(m)
}

var xxx_messageInfo_Star proto.InternalMessageInfo

func (m *Star) GetStarId() string {
	if m != nil {
		return m.StarId
	}
	return ""
}

func (m *Star) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Star) GetFacts() []*Facts {
	if m != nil {
		return m.Facts
	}
	return nil
}

func (m *Star) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Star) GetBasicInformation() *BasicInformation {
	if m != nil {
		return m.BasicInformation
	}
	return nil
}

type Facts struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Fact                 string   `protobuf:"bytes,2,opt,name=fact,proto3" json:"fact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facts) Reset()         { *m = Facts{} }
func (m *Facts) String() string { return proto.CompactTextString(m) }
func (*Facts) ProtoMessage()    {}
func (*Facts) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{1}
}

func (m *Facts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facts.Unmarshal(m, b)
}
func (m *Facts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facts.Marshal(b, m, deterministic)
}
func (m *Facts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facts.Merge(m, src)
}
func (m *Facts) XXX_Size() int {
	return xxx_messageInfo_Facts.Size(m)
}
func (m *Facts) XXX_DiscardUnknown() {
	xxx_messageInfo_Facts.DiscardUnknown(m)
}

var xxx_messageInfo_Facts proto.InternalMessageInfo

func (m *Facts) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Facts) GetFact() string {
	if m != nil {
		return m.Fact
	}
	return ""
}

type ListStarRequestFilter struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStarRequestFilter) Reset()         { *m = ListStarRequestFilter{} }
func (m *ListStarRequestFilter) String() string { return proto.CompactTextString(m) }
func (*ListStarRequestFilter) ProtoMessage()    {}
func (*ListStarRequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{2}
}

func (m *ListStarRequestFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStarRequestFilter.Unmarshal(m, b)
}
func (m *ListStarRequestFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStarRequestFilter.Marshal(b, m, deterministic)
}
func (m *ListStarRequestFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStarRequestFilter.Merge(m, src)
}
func (m *ListStarRequestFilter) XXX_Size() int {
	return xxx_messageInfo_ListStarRequestFilter.Size(m)
}
func (m *ListStarRequestFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStarRequestFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ListStarRequestFilter proto.InternalMessageInfo

func (m *ListStarRequestFilter) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *ListStarRequestFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BasicInformation struct {
	Mass                 string   `protobuf:"bytes,1,opt,name=mass,proto3" json:"mass,omitempty"`
	Classification       string   `protobuf:"bytes,2,opt,name=classification,proto3" json:"classification,omitempty"`
	Radius               string   `protobuf:"bytes,3,opt,name=radius,proto3" json:"radius,omitempty"`
	System               string   `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Temperature          string   `protobuf:"bytes,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Age                  string   `protobuf:"bytes,6,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicInformation) Reset()         { *m = BasicInformation{} }
func (m *BasicInformation) String() string { return proto.CompactTextString(m) }
func (*BasicInformation) ProtoMessage()    {}
func (*BasicInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{3}
}

func (m *BasicInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicInformation.Unmarshal(m, b)
}
func (m *BasicInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicInformation.Marshal(b, m, deterministic)
}
func (m *BasicInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicInformation.Merge(m, src)
}
func (m *BasicInformation) XXX_Size() int {
	return xxx_messageInfo_BasicInformation.Size(m)
}
func (m *BasicInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicInformation.DiscardUnknown(m)
}

var xxx_messageInfo_BasicInformation proto.InternalMessageInfo

func (m *BasicInformation) GetMass() string {
	if m != nil {
		return m.Mass
	}
	return ""
}

func (m *BasicInformation) GetClassification() string {
	if m != nil {
		return m.Classification
	}
	return ""
}

func (m *BasicInformation) GetRadius() string {
	if m != nil {
		return m.Radius
	}
	return ""
}

func (m *BasicInformation) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

func (m *BasicInformation) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *BasicInformation) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

type ReadStarRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStarRequest) Reset()         { *m = ReadStarRequest{} }
func (m *ReadStarRequest) String() string { return proto.CompactTextString(m) }
func (*ReadStarRequest) ProtoMessage()    {}
func (*ReadStarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{4}
}

func (m *ReadStarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStarRequest.Unmarshal(m, b)
}
func (m *ReadStarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStarRequest.Marshal(b, m, deterministic)
}
func (m *ReadStarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStarRequest.Merge(m, src)
}
func (m *ReadStarRequest) XXX_Size() int {
	return xxx_messageInfo_ReadStarRequest.Size(m)
}
func (m *ReadStarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStarRequest proto.InternalMessageInfo

func (m *ReadStarRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReadStarResponse struct {
	Star                 *Star    `protobuf:"bytes,1,opt,name=star,proto3" json:"star,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStarResponse) Reset()         { *m = ReadStarResponse{} }
func (m *ReadStarResponse) String() string { return proto.CompactTextString(m) }
func (*ReadStarResponse) ProtoMessage()    {}
func (*ReadStarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{5}
}

func (m *ReadStarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStarResponse.Unmarshal(m, b)
}
func (m *ReadStarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStarResponse.Marshal(b, m, deterministic)
}
func (m *ReadStarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStarResponse.Merge(m, src)
}
func (m *ReadStarResponse) XXX_Size() int {
	return xxx_messageInfo_ReadStarResponse.Size(m)
}
func (m *ReadStarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStarResponse proto.InternalMessageInfo

func (m *ReadStarResponse) GetStar() *Star {
	if m != nil {
		return m.Star
	}
	return nil
}

type ListStarRequest struct {
	Skip                  int64                    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	ListStarRequestFilter []*ListStarRequestFilter `protobuf:"bytes,2,rep,name=list_star_request_filter,json=listStarRequestFilter,proto3" json:"list_star_request_filter,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *ListStarRequest) Reset()         { *m = ListStarRequest{} }
func (m *ListStarRequest) String() string { return proto.CompactTextString(m) }
func (*ListStarRequest) ProtoMessage()    {}
func (*ListStarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{6}
}

func (m *ListStarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStarRequest.Unmarshal(m, b)
}
func (m *ListStarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStarRequest.Marshal(b, m, deterministic)
}
func (m *ListStarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStarRequest.Merge(m, src)
}
func (m *ListStarRequest) XXX_Size() int {
	return xxx_messageInfo_ListStarRequest.Size(m)
}
func (m *ListStarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStarRequest proto.InternalMessageInfo

func (m *ListStarRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListStarRequest) GetListStarRequestFilter() []*ListStarRequestFilter {
	if m != nil {
		return m.ListStarRequestFilter
	}
	return nil
}

type ListStarResponse struct {
	Star                 []*Star  `protobuf:"bytes,1,rep,name=star,proto3" json:"star,omitempty"`
	NumberOfDocuments    int64    `protobuf:"varint,2,opt,name=number_of_documents,json=numberOfDocuments,proto3" json:"number_of_documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStarResponse) Reset()         { *m = ListStarResponse{} }
func (m *ListStarResponse) String() string { return proto.CompactTextString(m) }
func (*ListStarResponse) ProtoMessage()    {}
func (*ListStarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_209433b2398247ba, []int{7}
}

func (m *ListStarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStarResponse.Unmarshal(m, b)
}
func (m *ListStarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStarResponse.Marshal(b, m, deterministic)
}
func (m *ListStarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStarResponse.Merge(m, src)
}
func (m *ListStarResponse) XXX_Size() int {
	return xxx_messageInfo_ListStarResponse.Size(m)
}
func (m *ListStarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStarResponse proto.InternalMessageInfo

func (m *ListStarResponse) GetStar() []*Star {
	if m != nil {
		return m.Star
	}
	return nil
}

func (m *ListStarResponse) GetNumberOfDocuments() int64 {
	if m != nil {
		return m.NumberOfDocuments
	}
	return 0
}

func init() {
	proto.RegisterType((*Star)(nil), "star.Star")
	proto.RegisterType((*Facts)(nil), "star.Facts")
	proto.RegisterType((*ListStarRequestFilter)(nil), "star.ListStarRequestFilter")
	proto.RegisterType((*BasicInformation)(nil), "star.BasicInformation")
	proto.RegisterType((*ReadStarRequest)(nil), "star.ReadStarRequest")
	proto.RegisterType((*ReadStarResponse)(nil), "star.ReadStarResponse")
	proto.RegisterType((*ListStarRequest)(nil), "star.ListStarRequest")
	proto.RegisterType((*ListStarResponse)(nil), "star.ListStarResponse")
}

func init() {
	proto.RegisterFile("star/starpb/star.proto", fileDescriptor_209433b2398247ba)
}

var fileDescriptor_209433b2398247ba = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0x9b, 0x99, 0x38, 0x5b, 0x01, 0x37, 0xdb, 0x3a, 0x63, 0x50, 0x90, 0x31, 0xa0, 0xcc,
	0x69, 0xc4, 0x78, 0xda, 0xeb, 0xaa, 0x03, 0x0b, 0x82, 0x90, 0xf5, 0xe4, 0x25, 0x74, 0x92, 0x8e,
	0x34, 0xe6, 0xcb, 0xee, 0xce, 0x82, 0x78, 0xf4, 0x17, 0xe9, 0x2f, 0x94, 0xaa, 0x4e, 0x3b, 0x4b,
	0x9c, 0xcb, 0x4c, 0xd5, 0xab, 0xaa, 0xd7, 0xaf, 0x3e, 0x02, 0x1b, 0x6d, 0xb8, 0x7a, 0x8d, 0x3f,
	0x43, 0x41, 0x7f, 0xfb, 0x41, 0xf5, 0xa6, 0x67, 0x0b, 0xb4, 0x93, 0xdf, 0x1e, 0x2c, 0x6e, 0x0d,
	0x57, 0xec, 0x09, 0x3c, 0x40, 0x20, 0x97, 0x55, 0xec, 0x6d, 0xbd, 0xdd, 0x79, 0x16, 0xa0, 0x7b,
	0x53, 0x31, 0x06, 0x8b, 0x8e, 0xb7, 0x22, 0x3e, 0x23, 0x94, 0x6c, 0xf6, 0x02, 0x96, 0x35, 0x2f,
	0x8d, 0x8e, 0xfd, 0xad, 0xbf, 0x0b, 0xd3, 0x70, 0x4f, 0xbc, 0x07, 0x84, 0x32, 0x1b, 0x61, 0x8f,
	0x61, 0x29, 0x5b, 0xfe, 0x55, 0xc4, 0x0b, 0xaa, 0xb3, 0x0e, 0x7b, 0x07, 0x97, 0x05, 0xd7, 0xb2,
	0xcc, 0x65, 0x57, 0xf7, 0xaa, 0xe5, 0x46, 0xf6, 0x5d, 0xbc, 0xdc, 0x7a, 0xbb, 0x30, 0xdd, 0x58,
	0x92, 0x6b, 0x0c, 0xdf, 0x1c, 0xa3, 0x59, 0x54, 0xcc, 0x90, 0xe4, 0x0d, 0x2c, 0x0f, 0xee, 0x0d,
	0x23, 0x4d, 0x23, 0x26, 0xc5, 0xd6, 0x41, 0xc1, 0x28, 0xc1, 0x09, 0x46, 0x3b, 0xf9, 0x00, 0xeb,
	0x8f, 0x52, 0x1b, 0xec, 0x34, 0x13, 0xdf, 0x47, 0xa1, 0xcd, 0x41, 0x36, 0x46, 0x28, 0xb6, 0x81,
	0xa0, 0xec, 0x9b, 0xb1, 0xed, 0x5c, 0xd7, 0xd6, 0x43, 0xea, 0x3b, 0xde, 0x8c, 0xae, 0x6d, 0xeb,
	0x24, 0x7f, 0x3c, 0x88, 0xe6, 0x02, 0xf1, 0xbd, 0x96, 0x6b, 0x3d, 0x11, 0x90, 0xcd, 0x5e, 0xc1,
	0xc3, 0xb2, 0xe1, 0x5a, 0xcb, 0x5a, 0x96, 0xb6, 0x49, 0xcb, 0x33, 0x43, 0xf1, 0x79, 0xc5, 0x2b,
	0x39, 0xe2, 0x24, 0xe9, 0x79, 0xeb, 0x21, 0xae, 0x7f, 0x68, 0x23, 0xda, 0x69, 0x7c, 0x93, 0xc7,
	0xb6, 0x10, 0x1a, 0xd1, 0x0e, 0x42, 0x71, 0x33, 0x2a, 0x41, 0x93, 0x3b, 0xcf, 0xee, 0x43, 0x2c,
	0x02, 0x1f, 0xa7, 0x1e, 0x50, 0x04, 0xcd, 0xe4, 0x25, 0x5c, 0x64, 0x82, 0x57, 0xf7, 0x7a, 0xff,
	0xb7, 0x53, 0xef, 0xb8, 0xd3, 0x24, 0x85, 0xe8, 0x98, 0xa6, 0x87, 0xbe, 0xd3, 0x82, 0x3d, 0x07,
	0xba, 0x12, 0xca, 0x0b, 0x53, 0xb0, 0x1b, 0xa2, 0x0c, 0x7b, 0x3d, 0x3f, 0xe1, 0x62, 0x36, 0x56,
	0xa4, 0xd6, 0xdf, 0xe4, 0x40, 0x25, 0x7e, 0x46, 0x36, 0xfb, 0x0c, 0x71, 0x23, 0xb5, 0xc9, 0xe9,
	0xc0, 0x94, 0x4d, 0xcc, 0x6b, 0x5a, 0x40, 0x7c, 0x46, 0x17, 0xf4, 0xcc, 0x52, 0x9f, 0xdc, 0x51,
	0xb6, 0x6e, 0x4e, 0xc1, 0x49, 0x01, 0xd1, 0x31, 0xff, 0x3f, 0xc1, 0xfe, 0x29, 0xc1, 0x6c, 0x0f,
	0x8f, 0xba, 0xb1, 0x2d, 0x84, 0xca, 0xfb, 0x3a, 0xaf, 0xfa, 0x72, 0x6c, 0x45, 0x67, 0x34, 0x2d,
	0xc7, 0xcf, 0x2e, 0x6d, 0xe8, 0x53, 0xfd, 0xde, 0x05, 0xd2, 0x5f, 0x1e, 0x84, 0x58, 0x7e, 0x2b,
	0xd4, 0x9d, 0x2c, 0x05, 0xbb, 0x82, 0x95, 0x1b, 0x12, 0x5b, 0x5b, 0xf6, 0xd9, 0x6c, 0x9f, 0x6e,
	0xe6, 0xf0, 0x24, 0xed, 0x0a, 0x56, 0x4e, 0xae, 0x2b, 0x9d, 0xb5, 0xeb, 0x4a, 0xe7, 0x5d, 0x5d,
	0xaf, 0xbe, 0x04, 0xf6, 0xfb, 0x2d, 0x02, 0xfa, 0x76, 0xdf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x9f, 0x6e, 0x09, 0xd5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StarServiceClient is the client API for StarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StarServiceClient interface {
	ReadStar(ctx context.Context, in *ReadStarRequest, opts ...grpc.CallOption) (*ReadStarResponse, error)
	ListStar(ctx context.Context, in *ListStarRequest, opts ...grpc.CallOption) (*ListStarResponse, error)
}

type starServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarServiceClient(cc grpc.ClientConnInterface) StarServiceClient {
	return &starServiceClient{cc}
}

func (c *starServiceClient) ReadStar(ctx context.Context, in *ReadStarRequest, opts ...grpc.CallOption) (*ReadStarResponse, error) {
	out := new(ReadStarResponse)
	err := c.cc.Invoke(ctx, "/star.StarService/ReadStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starServiceClient) ListStar(ctx context.Context, in *ListStarRequest, opts ...grpc.CallOption) (*ListStarResponse, error) {
	out := new(ListStarResponse)
	err := c.cc.Invoke(ctx, "/star.StarService/ListStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarServiceServer is the server API for StarService service.
type StarServiceServer interface {
	ReadStar(context.Context, *ReadStarRequest) (*ReadStarResponse, error)
	ListStar(context.Context, *ListStarRequest) (*ListStarResponse, error)
}

// UnimplementedStarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStarServiceServer struct {
}

func (*UnimplementedStarServiceServer) ReadStar(ctx context.Context, req *ReadStarRequest) (*ReadStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadStar not implemented")
}
func (*UnimplementedStarServiceServer) ListStar(ctx context.Context, req *ListStarRequest) (*ListStarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStar not implemented")
}

func RegisterStarServiceServer(s *grpc.Server, srv StarServiceServer) {
	s.RegisterService(&_StarService_serviceDesc, srv)
}

func _StarService_ReadStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarServiceServer).ReadStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/star.StarService/ReadStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarServiceServer).ReadStar(ctx, req.(*ReadStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarService_ListStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarServiceServer).ListStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/star.StarService/ListStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarServiceServer).ListStar(ctx, req.(*ListStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "star.StarService",
	HandlerType: (*StarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadStar",
			Handler:    _StarService_ReadStar_Handler,
		},
		{
			MethodName: "ListStar",
			Handler:    _StarService_ListStar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "star/starpb/star.proto",
}
