// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nasa/nasapb/nasa.proto

package nasapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// APOD - Astronomy Picture of the Day - Data is pulled from NASA API once per day and saved in our mongodb.
type APOD struct {
	CopyRight            string   `protobuf:"bytes,1,opt,name=copy_right,json=copyRight,proto3" json:"copy_right,omitempty"`
	Date                 int64    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Explanation          string   `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	HdUrl                string   `protobuf:"bytes,4,opt,name=hd_url,json=hdUrl,proto3" json:"hd_url,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APOD) Reset()         { *m = APOD{} }
func (m *APOD) String() string { return proto.CompactTextString(m) }
func (*APOD) ProtoMessage()    {}
func (*APOD) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{0}
}

func (m *APOD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APOD.Unmarshal(m, b)
}
func (m *APOD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APOD.Marshal(b, m, deterministic)
}
func (m *APOD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APOD.Merge(m, src)
}
func (m *APOD) XXX_Size() int {
	return xxx_messageInfo_APOD.Size(m)
}
func (m *APOD) XXX_DiscardUnknown() {
	xxx_messageInfo_APOD.DiscardUnknown(m)
}

var xxx_messageInfo_APOD proto.InternalMessageInfo

func (m *APOD) GetCopyRight() string {
	if m != nil {
		return m.CopyRight
	}
	return ""
}

func (m *APOD) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *APOD) GetExplanation() string {
	if m != nil {
		return m.Explanation
	}
	return ""
}

func (m *APOD) GetHdUrl() string {
	if m != nil {
		return m.HdUrl
	}
	return ""
}

func (m *APOD) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ReadAPODRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAPODRequest) Reset()         { *m = ReadAPODRequest{} }
func (m *ReadAPODRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAPODRequest) ProtoMessage()    {}
func (*ReadAPODRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{1}
}

func (m *ReadAPODRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAPODRequest.Unmarshal(m, b)
}
func (m *ReadAPODRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAPODRequest.Marshal(b, m, deterministic)
}
func (m *ReadAPODRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAPODRequest.Merge(m, src)
}
func (m *ReadAPODRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAPODRequest.Size(m)
}
func (m *ReadAPODRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAPODRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAPODRequest proto.InternalMessageInfo

type ReadAPODResponse struct {
	Apod                 *APOD    `protobuf:"bytes,1,opt,name=apod,proto3" json:"apod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAPODResponse) Reset()         { *m = ReadAPODResponse{} }
func (m *ReadAPODResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAPODResponse) ProtoMessage()    {}
func (*ReadAPODResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{2}
}

func (m *ReadAPODResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAPODResponse.Unmarshal(m, b)
}
func (m *ReadAPODResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAPODResponse.Marshal(b, m, deterministic)
}
func (m *ReadAPODResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAPODResponse.Merge(m, src)
}
func (m *ReadAPODResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAPODResponse.Size(m)
}
func (m *ReadAPODResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAPODResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAPODResponse proto.InternalMessageInfo

func (m *ReadAPODResponse) GetApod() *APOD {
	if m != nil {
		return m.Apod
	}
	return nil
}

func init() {
	proto.RegisterType((*APOD)(nil), "nasa.APOD")
	proto.RegisterType((*ReadAPODRequest)(nil), "nasa.ReadAPODRequest")
	proto.RegisterType((*ReadAPODResponse)(nil), "nasa.ReadAPODResponse")
}

func init() {
	proto.RegisterFile("nasa/nasapb/nasa.proto", fileDescriptor_a7107a1413a2812c)
}

var fileDescriptor_a7107a1413a2812c = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x9b, 0x2e, 0xed, 0x14, 0x51, 0x07, 0x5b, 0x82, 0xa0, 0x2c, 0x7b, 0xea, 0xa9,
	0xc2, 0x7a, 0xf2, 0xa8, 0x78, 0xf2, 0x62, 0x89, 0x78, 0xf1, 0x52, 0xd2, 0x66, 0x70, 0x17, 0x42,
	0x12, 0xb3, 0xa9, 0xe8, 0x3f, 0xf0, 0x67, 0x4b, 0x66, 0x11, 0xa5, 0x97, 0x64, 0xf2, 0x65, 0x92,
	0xf7, 0xe6, 0xc1, 0xc2, 0xe9, 0x5e, 0x5f, 0xe7, 0x25, 0x6c, 0x79, 0x5b, 0x85, 0xe8, 0x93, 0x47,
	0x91, 0xeb, 0xfa, 0xbb, 0x00, 0x71, 0xb7, 0x7e, 0x7a, 0xc0, 0x4b, 0x80, 0x9d, 0x0f, 0x5f, 0x9b,
	0xd8, 0xbd, 0xb5, 0x49, 0x16, 0x55, 0xb1, 0x9c, 0xaa, 0x69, 0x26, 0x2a, 0x03, 0x44, 0x10, 0x46,
	0x27, 0x92, 0x47, 0x55, 0xb1, 0x1c, 0x29, 0xae, 0xb1, 0x82, 0x19, 0x7d, 0x06, 0xab, 0x9d, 0x4e,
	0x9d, 0x77, 0x72, 0xc4, 0x6f, 0xfe, 0x23, 0x9c, 0x43, 0xd9, 0x9a, 0xcd, 0x3e, 0x5a, 0x29, 0xf8,
	0x72, 0xdc, 0x9a, 0x97, 0x68, 0xf1, 0x1c, 0xc6, 0xa9, 0x4b, 0x96, 0xe4, 0x78, 0xa0, 0x7c, 0xa8,
	0xcf, 0xe0, 0x44, 0x91, 0x36, 0xd9, 0x8d, 0xa2, 0xf7, 0x3d, 0xf5, 0xa9, 0x6e, 0xe0, 0xf4, 0x0f,
	0xf5, 0xc1, 0xbb, 0x9e, 0xf0, 0x0a, 0x84, 0x0e, 0xde, 0xb0, 0xc5, 0x59, 0x03, 0x2b, 0x1e, 0x89,
	0x3b, 0x98, 0x37, 0x8f, 0x70, 0xbc, 0xb6, 0xda, 0x51, 0x7a, 0xa6, 0xf8, 0xd1, 0xed, 0x08, 0x6f,
	0x61, 0xf2, 0xfb, 0x09, 0xce, 0x87, 0xf6, 0x03, 0x9d, 0x8b, 0xc5, 0x21, 0x1e, 0xb4, 0xee, 0x27,
	0xaf, 0xe5, 0x10, 0xdc, 0xb6, 0xe4, 0xd0, 0x6e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x9a,
	0xd5, 0x03, 0x4e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlanetServiceClient is the client API for PlanetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlanetServiceClient interface {
	ReadAPOD(ctx context.Context, in *ReadAPODRequest, opts ...grpc.CallOption) (*ReadAPODResponse, error)
}

type planetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanetServiceClient(cc grpc.ClientConnInterface) PlanetServiceClient {
	return &planetServiceClient{cc}
}

func (c *planetServiceClient) ReadAPOD(ctx context.Context, in *ReadAPODRequest, opts ...grpc.CallOption) (*ReadAPODResponse, error) {
	out := new(ReadAPODResponse)
	err := c.cc.Invoke(ctx, "/nasa.PlanetService/ReadAPOD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanetServiceServer is the server API for PlanetService service.
type PlanetServiceServer interface {
	ReadAPOD(context.Context, *ReadAPODRequest) (*ReadAPODResponse, error)
}

// UnimplementedPlanetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlanetServiceServer struct {
}

func (*UnimplementedPlanetServiceServer) ReadAPOD(ctx context.Context, req *ReadAPODRequest) (*ReadAPODResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAPOD not implemented")
}

func RegisterPlanetServiceServer(s *grpc.Server, srv PlanetServiceServer) {
	s.RegisterService(&_PlanetService_serviceDesc, srv)
}

func _PlanetService_ReadAPOD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAPODRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetServiceServer).ReadAPOD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nasa.PlanetService/ReadAPOD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetServiceServer).ReadAPOD(ctx, req.(*ReadAPODRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlanetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nasa.PlanetService",
	HandlerType: (*PlanetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAPOD",
			Handler:    _PlanetService_ReadAPOD_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nasa/nasapb/nasa.proto",
}
