// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nasa/nasapb/nasa.proto

package nasapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// APOD - Astronomy Picture of the Day - Data is pulled from NASA API once per day and saved in our mongodb.
type APOD struct {
	ApodId               string   `protobuf:"bytes,1,opt,name=apod_id,json=apodId,proto3" json:"apod_id,omitempty"`
	CopyRight            string   `protobuf:"bytes,2,opt,name=copy_right,json=copyRight,proto3" json:"copy_right,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Explanation          string   `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	HdUrl                string   `protobuf:"bytes,5,opt,name=hd_url,json=hdUrl,proto3" json:"hd_url,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APOD) Reset()         { *m = APOD{} }
func (m *APOD) String() string { return proto.CompactTextString(m) }
func (*APOD) ProtoMessage()    {}
func (*APOD) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{0}
}

func (m *APOD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APOD.Unmarshal(m, b)
}
func (m *APOD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APOD.Marshal(b, m, deterministic)
}
func (m *APOD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APOD.Merge(m, src)
}
func (m *APOD) XXX_Size() int {
	return xxx_messageInfo_APOD.Size(m)
}
func (m *APOD) XXX_DiscardUnknown() {
	xxx_messageInfo_APOD.DiscardUnknown(m)
}

var xxx_messageInfo_APOD proto.InternalMessageInfo

func (m *APOD) GetApodId() string {
	if m != nil {
		return m.ApodId
	}
	return ""
}

func (m *APOD) GetCopyRight() string {
	if m != nil {
		return m.CopyRight
	}
	return ""
}

func (m *APOD) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *APOD) GetExplanation() string {
	if m != nil {
		return m.Explanation
	}
	return ""
}

func (m *APOD) GetHdUrl() string {
	if m != nil {
		return m.HdUrl
	}
	return ""
}

func (m *APOD) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ListAPODRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAPODRequest) Reset()         { *m = ListAPODRequest{} }
func (m *ListAPODRequest) String() string { return proto.CompactTextString(m) }
func (*ListAPODRequest) ProtoMessage()    {}
func (*ListAPODRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{1}
}

func (m *ListAPODRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAPODRequest.Unmarshal(m, b)
}
func (m *ListAPODRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAPODRequest.Marshal(b, m, deterministic)
}
func (m *ListAPODRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAPODRequest.Merge(m, src)
}
func (m *ListAPODRequest) XXX_Size() int {
	return xxx_messageInfo_ListAPODRequest.Size(m)
}
func (m *ListAPODRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAPODRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAPODRequest proto.InternalMessageInfo

type ListAPODResponse struct {
	Apod                 []*APOD  `protobuf:"bytes,1,rep,name=apod,proto3" json:"apod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAPODResponse) Reset()         { *m = ListAPODResponse{} }
func (m *ListAPODResponse) String() string { return proto.CompactTextString(m) }
func (*ListAPODResponse) ProtoMessage()    {}
func (*ListAPODResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{2}
}

func (m *ListAPODResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAPODResponse.Unmarshal(m, b)
}
func (m *ListAPODResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAPODResponse.Marshal(b, m, deterministic)
}
func (m *ListAPODResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAPODResponse.Merge(m, src)
}
func (m *ListAPODResponse) XXX_Size() int {
	return xxx_messageInfo_ListAPODResponse.Size(m)
}
func (m *ListAPODResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAPODResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAPODResponse proto.InternalMessageInfo

func (m *ListAPODResponse) GetApod() []*APOD {
	if m != nil {
		return m.Apod
	}
	return nil
}

func init() {
	proto.RegisterType((*APOD)(nil), "nasa.APOD")
	proto.RegisterType((*ListAPODRequest)(nil), "nasa.ListAPODRequest")
	proto.RegisterType((*ListAPODResponse)(nil), "nasa.ListAPODResponse")
}

func init() {
	proto.RegisterFile("nasa/nasapb/nasa.proto", fileDescriptor_a7107a1413a2812c)
}

var fileDescriptor_a7107a1413a2812c = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x10, 0x80, 0xe9, 0xbf, 0x69, 0xfe, 0xdd, 0xe9, 0x41, 0x1d, 0xdc, 0x35, 0x08, 0x4a, 0xe9, 0x69,
	0x4f, 0x2b, 0xd4, 0x93, 0x47, 0xc5, 0x83, 0x82, 0xa8, 0x54, 0xbc, 0x78, 0x29, 0xd9, 0x4d, 0xb0,
	0x81, 0xd2, 0xc4, 0x24, 0x2b, 0xfa, 0x38, 0xbe, 0xa9, 0x64, 0x8a, 0x28, 0x7b, 0x49, 0x66, 0xbe,
	0x6f, 0xc8, 0x4c, 0x06, 0x16, 0x83, 0x0c, 0xf2, 0x2c, 0x1d, 0x6e, 0x4d, 0xd7, 0xca, 0x79, 0x1b,
	0x2d, 0xb2, 0x14, 0x57, 0x5f, 0x19, 0xb0, 0xcb, 0xc7, 0x87, 0x6b, 0x3c, 0x82, 0xff, 0xd2, 0x59,
	0xd5, 0x1a, 0x25, 0xb2, 0x32, 0x5b, 0xce, 0x1a, 0x9e, 0xd2, 0x5b, 0x85, 0x27, 0x00, 0x1b, 0xeb,
	0x3e, 0x5b, 0x6f, 0x5e, 0xbb, 0x28, 0xfe, 0x91, 0x9b, 0x25, 0xd2, 0x24, 0x80, 0x08, 0x4c, 0xc9,
	0xa8, 0xc5, 0x84, 0x04, 0xc5, 0x58, 0x42, 0xa1, 0x3f, 0x5c, 0x2f, 0x07, 0x19, 0x8d, 0x1d, 0x04,
	0x23, 0xf5, 0x17, 0xe1, 0x1c, 0x78, 0xa7, 0xda, 0xad, 0xef, 0x45, 0x4e, 0x32, 0xef, 0xd4, 0xb3,
	0xef, 0xf1, 0x10, 0xf2, 0x68, 0x62, 0xaf, 0x05, 0x1f, 0x29, 0x25, 0xd5, 0x01, 0xec, 0xdd, 0x99,
	0x10, 0xd3, 0x98, 0x8d, 0x7e, 0xdb, 0xea, 0x10, 0xab, 0x1a, 0xf6, 0x7f, 0x51, 0x70, 0x76, 0x08,
	0x1a, 0x4f, 0x81, 0xa5, 0x91, 0x45, 0x56, 0x4e, 0x96, 0x45, 0x0d, 0x2b, 0xfa, 0x2b, 0x55, 0x10,
	0xaf, 0x6f, 0xa0, 0xb8, 0x97, 0x41, 0x3e, 0x69, 0xff, 0x6e, 0x36, 0x1a, 0x2f, 0x60, 0xfa, 0xf3,
	0x04, 0xce, 0xc7, 0xe2, 0x9d, 0x2e, 0xc7, 0x8b, 0x5d, 0x3c, 0x76, 0xba, 0x9a, 0xbe, 0xf0, 0x71,
	0x9f, 0x6b, 0x4e, 0xbb, 0x3c, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x08, 0x9d, 0x12, 0x65,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NasaServiceClient is the client API for NasaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NasaServiceClient interface {
	ListAPOD(ctx context.Context, in *ListAPODRequest, opts ...grpc.CallOption) (*ListAPODResponse, error)
}

type nasaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNasaServiceClient(cc grpc.ClientConnInterface) NasaServiceClient {
	return &nasaServiceClient{cc}
}

func (c *nasaServiceClient) ListAPOD(ctx context.Context, in *ListAPODRequest, opts ...grpc.CallOption) (*ListAPODResponse, error) {
	out := new(ListAPODResponse)
	err := c.cc.Invoke(ctx, "/nasa.NasaService/ListAPOD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NasaServiceServer is the server API for NasaService service.
type NasaServiceServer interface {
	ListAPOD(context.Context, *ListAPODRequest) (*ListAPODResponse, error)
}

// UnimplementedNasaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNasaServiceServer struct {
}

func (*UnimplementedNasaServiceServer) ListAPOD(ctx context.Context, req *ListAPODRequest) (*ListAPODResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAPOD not implemented")
}

func RegisterNasaServiceServer(s *grpc.Server, srv NasaServiceServer) {
	s.RegisterService(&_NasaService_serviceDesc, srv)
}

func _NasaService_ListAPOD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPODRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NasaServiceServer).ListAPOD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nasa.NasaService/ListAPOD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NasaServiceServer).ListAPOD(ctx, req.(*ListAPODRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NasaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nasa.NasaService",
	HandlerType: (*NasaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAPOD",
			Handler:    _NasaService_ListAPOD_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nasa/nasapb/nasa.proto",
}
