// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nasa/nasapb/nasa.proto

package nasapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// APOD - Astronomy Picture of the Day - Data is pulled from NASA API once per day and saved in our mongodb.
type APOD struct {
	ApodId               string   `protobuf:"bytes,1,opt,name=apod_id,json=apodId,proto3" json:"apod_id,omitempty"`
	CopyRight            string   `protobuf:"bytes,2,opt,name=copy_right,json=copyRight,proto3" json:"copy_right,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Explanation          string   `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	HdUrl                string   `protobuf:"bytes,5,opt,name=hd_url,json=hdUrl,proto3" json:"hd_url,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APOD) Reset()         { *m = APOD{} }
func (m *APOD) String() string { return proto.CompactTextString(m) }
func (*APOD) ProtoMessage()    {}
func (*APOD) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{0}
}

func (m *APOD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APOD.Unmarshal(m, b)
}
func (m *APOD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APOD.Marshal(b, m, deterministic)
}
func (m *APOD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APOD.Merge(m, src)
}
func (m *APOD) XXX_Size() int {
	return xxx_messageInfo_APOD.Size(m)
}
func (m *APOD) XXX_DiscardUnknown() {
	xxx_messageInfo_APOD.DiscardUnknown(m)
}

var xxx_messageInfo_APOD proto.InternalMessageInfo

func (m *APOD) GetApodId() string {
	if m != nil {
		return m.ApodId
	}
	return ""
}

func (m *APOD) GetCopyRight() string {
	if m != nil {
		return m.CopyRight
	}
	return ""
}

func (m *APOD) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *APOD) GetExplanation() string {
	if m != nil {
		return m.Explanation
	}
	return ""
}

func (m *APOD) GetHdUrl() string {
	if m != nil {
		return m.HdUrl
	}
	return ""
}

func (m *APOD) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ReadAPODRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAPODRequest) Reset()         { *m = ReadAPODRequest{} }
func (m *ReadAPODRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAPODRequest) ProtoMessage()    {}
func (*ReadAPODRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{1}
}

func (m *ReadAPODRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAPODRequest.Unmarshal(m, b)
}
func (m *ReadAPODRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAPODRequest.Marshal(b, m, deterministic)
}
func (m *ReadAPODRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAPODRequest.Merge(m, src)
}
func (m *ReadAPODRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAPODRequest.Size(m)
}
func (m *ReadAPODRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAPODRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAPODRequest proto.InternalMessageInfo

type ReadAPODResponse struct {
	Apod                 *APOD    `protobuf:"bytes,1,opt,name=apod,proto3" json:"apod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAPODResponse) Reset()         { *m = ReadAPODResponse{} }
func (m *ReadAPODResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAPODResponse) ProtoMessage()    {}
func (*ReadAPODResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7107a1413a2812c, []int{2}
}

func (m *ReadAPODResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAPODResponse.Unmarshal(m, b)
}
func (m *ReadAPODResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAPODResponse.Marshal(b, m, deterministic)
}
func (m *ReadAPODResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAPODResponse.Merge(m, src)
}
func (m *ReadAPODResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAPODResponse.Size(m)
}
func (m *ReadAPODResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAPODResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAPODResponse proto.InternalMessageInfo

func (m *ReadAPODResponse) GetApod() *APOD {
	if m != nil {
		return m.Apod
	}
	return nil
}

func init() {
	proto.RegisterType((*APOD)(nil), "nasa.APOD")
	proto.RegisterType((*ReadAPODRequest)(nil), "nasa.ReadAPODRequest")
	proto.RegisterType((*ReadAPODResponse)(nil), "nasa.ReadAPODResponse")
}

func init() {
	proto.RegisterFile("nasa/nasapb/nasa.proto", fileDescriptor_a7107a1413a2812c)
}

var fileDescriptor_a7107a1413a2812c = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0xdb, 0xc6, 0xdd, 0xe9, 0x41, 0x1d, 0xdc, 0x35, 0x08, 0x4a, 0xe9, 0x69, 0x4f,
	0x2b, 0xd4, 0x93, 0x47, 0xc5, 0x83, 0x5e, 0x54, 0x22, 0x5e, 0xbc, 0x94, 0xec, 0x26, 0xd8, 0x40,
	0x69, 0x62, 0x92, 0x15, 0x7d, 0x1c, 0xdf, 0x54, 0x32, 0x45, 0x94, 0xbd, 0x24, 0x33, 0xdf, 0x4c,
	0x32, 0xff, 0xfc, 0xb0, 0x18, 0x64, 0x90, 0x17, 0xe9, 0x70, 0x6b, 0xba, 0x56, 0xce, 0xdb, 0x68,
	0x31, 0x4f, 0x71, 0xfd, 0x9d, 0x41, 0x7e, 0xfd, 0xf4, 0x78, 0x8b, 0x27, 0xb0, 0x2f, 0x9d, 0x55,
	0xad, 0x51, 0x3c, 0xab, 0xb2, 0xe5, 0x4c, 0xb0, 0x94, 0xde, 0x2b, 0x3c, 0x03, 0xd8, 0x58, 0xf7,
	0xd5, 0x7a, 0xf3, 0xd6, 0x45, 0xbe, 0x47, 0xb5, 0x59, 0x22, 0x22, 0x01, 0x44, 0xc8, 0x95, 0x8c,
	0x9a, 0x4f, 0xaa, 0x6c, 0x39, 0x11, 0x14, 0x63, 0x05, 0xa5, 0xfe, 0x74, 0xbd, 0x1c, 0x64, 0x34,
	0x76, 0xe0, 0x39, 0xbd, 0xf9, 0x8f, 0x70, 0x0e, 0xac, 0x53, 0xed, 0xd6, 0xf7, 0xbc, 0xa0, 0x62,
	0xd1, 0xa9, 0x17, 0xdf, 0xe3, 0x31, 0x14, 0xd1, 0xc4, 0x5e, 0x73, 0x36, 0x52, 0x4a, 0xea, 0x23,
	0x38, 0x10, 0x5a, 0xaa, 0x24, 0x53, 0xe8, 0xf7, 0xad, 0x0e, 0xb1, 0x6e, 0xe0, 0xf0, 0x0f, 0x05,
	0x67, 0x87, 0xa0, 0xf1, 0x1c, 0xf2, 0x24, 0x99, 0xe4, 0x97, 0x0d, 0xac, 0x68, 0x57, 0xea, 0x20,
	0xde, 0xdc, 0x41, 0xf9, 0x20, 0x83, 0x7c, 0xd6, 0xfe, 0xc3, 0x6c, 0x34, 0x5e, 0xc1, 0xf4, 0xf7,
	0x0b, 0x9c, 0x8f, 0xcd, 0x3b, 0x53, 0x4e, 0x17, 0xbb, 0x78, 0x9c, 0x74, 0x33, 0x7d, 0x65, 0xa3,
	0x9f, 0x6b, 0x46, 0x5e, 0x5e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x24, 0x7c, 0xc3, 0x65,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NasaServiceClient is the client API for NasaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NasaServiceClient interface {
	ReadAPOD(ctx context.Context, in *ReadAPODRequest, opts ...grpc.CallOption) (*ReadAPODResponse, error)
}

type nasaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNasaServiceClient(cc grpc.ClientConnInterface) NasaServiceClient {
	return &nasaServiceClient{cc}
}

func (c *nasaServiceClient) ReadAPOD(ctx context.Context, in *ReadAPODRequest, opts ...grpc.CallOption) (*ReadAPODResponse, error) {
	out := new(ReadAPODResponse)
	err := c.cc.Invoke(ctx, "/nasa.NasaService/ReadAPOD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NasaServiceServer is the server API for NasaService service.
type NasaServiceServer interface {
	ReadAPOD(context.Context, *ReadAPODRequest) (*ReadAPODResponse, error)
}

// UnimplementedNasaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNasaServiceServer struct {
}

func (*UnimplementedNasaServiceServer) ReadAPOD(ctx context.Context, req *ReadAPODRequest) (*ReadAPODResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAPOD not implemented")
}

func RegisterNasaServiceServer(s *grpc.Server, srv NasaServiceServer) {
	s.RegisterService(&_NasaService_serviceDesc, srv)
}

func _NasaService_ReadAPOD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAPODRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NasaServiceServer).ReadAPOD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nasa.NasaService/ReadAPOD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NasaServiceServer).ReadAPOD(ctx, req.(*ReadAPODRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NasaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nasa.NasaService",
	HandlerType: (*NasaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAPOD",
			Handler:    _NasaService_ReadAPOD_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nasa/nasapb/nasa.proto",
}
